on:
  schedule:
    - cron: '*/15 * * * *'

project:
  type: website
  output-dir: docs
  render:
   - index.qmd


website:
  title: "MeteoMTP"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



