on:
  schedule:
    - cron: '*/15 * * * *'

project:
  type: website
  output-dir: docs
  render:
   - index.qmd


website:
  title: "MeteoMTP"
  page-navigation: true
  repo-url: https://julesbatallerbeltran.github.io/MeteoMTP/
  repo-actions: [source, issue]
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
execute:
  echo: false  

jupyter: python3


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



